### ISSUE TITLE
A dentist can manage their information

### ISSUE THREAD

**Issue by Pcushing** [Pcushing/pycky#7]
Needs a list of attributes/types/examples. For example:
* title, ex., Periodontist, Dental Hygienist, etc.
* accepts_emergency_appointments, yes/no
* ... etc.

**Comment by Pycky** [comment]
I'm trying to understand which page this will be. So after a dentist decides to be added as a dentist or a dental office page - this will be a page where they can answer questions so that is shown on their profile page? Is that right? 

Dentist Page Questions:

1. Specialty
Options: General Dentist, Periodontist, Pedodontist, Oral Surgeon, Orthodontist, Sleep Dentistry, Endodontist, TMJ Specialist
2. Location
The address of each office they work at. 
    a. associate vs. b. owner of that practice
Click a link to connect with the office - if the office is already on our map initially from our scrapped dental office in SF. 
3. Hours of operation of each office that they work at that they have listed and how many days a week are they at each practice
M, T, W, R, F, S, S, -- I am thinking click box and then enter hours that they are seeing patients at each particular office that they list. 
4. Hours available for emergency appointments
---same thing have them click day box, and set times for each office
5. Email/Phone number of individual dentist - (if they want to list any of their personal information visible, otherwise they don't have to have these things visible)
6. Who is in your specialist network - tab? 
       Where they can list their specialists they reffer to and their specialists webpage, allowing for Pycky.com to send this specialist a link stating, join pycky.com you were just referred by your General Dentist
7. enter a profile picture, enter a cover photo picture of anything they want. 
8. link to their yelp reviews if they have indiividual yelp reviews. 

I think its all on here: http://pycky.com/patient/patient_doctor_view.html

An area to have them type in their services they provide, and their awards that differentiate themselves. 

The insurance portion will be linked to each office. So once the office is claimed by the dentist, the dentist can enter the insurance that they are in networking with at that office into an insurance tab after claiming the office.
Financial/Insurance  - Maybe we can have an area where they enter all of their insurance they are in networking with and then in the future new dentists can have that option populate? For me to find all insurance options - it might be tough. I think we should start with a couple and give dentists the ability to enter their insurance will can be saved in our system for future dentists?)
Cash, Delta Dental of CA PPO, Cigna PPO, Delta Dental Premiere, Aetna PPO, United Healthcare PPO, Metlife PPO, Blue Anthem PPO, Blue Cross of CA PPO

This way if its based on each office once the office is claimed - after we have a database of insurance options entered by dentists - they will be visible and available for patients to click on when looking to book an appointment or find a dentist that accepts their insurance. 

So after they sign up as an individual dentist (which can be one day to approach it) The second way would also be to simply CLAIM their office listing - Since we plan on having some scrapped from a database of SF dentists off the bat, right? If their office is already on the map - they Claim it as a dentist, enter all of this above information as a dentist so that they create their "dentist profile" Then they link to their office page once they have claimed it and verified that they own the office. This verification can be a phone call to their office line? Or an email to their office email address to verify ownership.  They then can have a link on their dentist profile stating - book an appt. with this dentist at this office. Similarly from the office page - book an appointment with this dentist - which then links from the office page to the individual dentist page to book the appt.

Order: 
http://pycky.com/patient/patient_clinic_view.html
http://pycky.com/patient/patient_doctor_view.html

You can see here that the offices on the map will be pulled from the database, with initially no doctors connected to them because the doctors will need to be added individually which will also cause them to make their profile pages. They will link with each office that they are an owner or associate at - then their individual profile pages will have more specific information pertaining to them as an individual.

**Comment by Pcushing** [comment]
http://pycky.com/patient/patient_doctor_view.html
http://pycky.com/patient/patient_clinic_view.html

These are exactly what I've been looking for, but I'm not at all sure how to get to these in the current pycky.com site. When I go here http://pycky.com/patient/patient_search.html and click on the two results at the bottom, I'm not taken anywhere (which is where i'd expect them). If i click book-an-appointment, I get a modal. Where are these pages linked?

Answering your specific questions now but those two links fill a big gap for me as I couldnt find them anywhere.

> So after a dentist decides to be added as a dentist or a dental office page - this will be a page where they can answer questions so that is shown on their profile page? Is that right?

Yes. This is probably two different views/experiences that are missing. 

1. The onboarding experience. If I'm a new dentist to Pycky, I come to pycky.com, click on the "I am a ... Doctor" button, and then I should be prompted to start setting up my account, including creating a login. The mocks just throw us into a completed account that already has appointments. 

2. Once they are set up, they'd likely need to change this information over time. Presumably, the Profile tab here (http://pycky.com/doctor/doctor_cal.html#) would be the place to do it, but it's not built out. I can see now what it should look like to the patient -- http://pycky.com/patient/patient_doctor_view.html -- but if the doctor needs to update this, what's it look like? 

I've got very similar questions for https://github.com/Pcushing/pycky/issues/6 since we're missing similar info. How does one set up / join an office as a dentist? How do they edit it over time?

> Since we plan on having some scrapped from a database of SF dentists off the bat, right?

Even if we do, we should design for adding dentists without ay information to start.  As soon as the site starts supporting invitations, we'll get people invited who have no data in the system so we need to design around that. If someone's data is scraped in, great, we make it easier for them. It's more of an enhanced experience than the default.

> If their office is already on the map - they Claim it as a dentist, enter all of this above information as a dentist so that they create their "dentist profile" 

This Claim process is something I'd love to see mocked up before I build.

> You can see here that the offices on the map will be pulled from the database, with initially no doctors connected to them because the doctors will need to be added individually

Again, I'd assume this is an enhanced experience. Assume someone joins without an office already in the database. How would we set up an office then? What would it look like?

CC @Pycky

**Comment by Pycky** [comment]
Hi - 

When you go to http://pycky.com/patient/patient_search.html   click search at the top.  This will take you to the Skoulas Dentistry page (office page) Then you can click on the individual doctor and it 
will take you to the doctor page. 

I just emailed Sean but this is how I see it: 

If their office is already on the map - they Claim it as a dentist, enter all of this above information as a dentist so that they create their "dentist profile"
This Claim process is something I'd love to see mocked up before I build.

You can see here that the offices on the map will be pulled from the database, with initially no doctors connected to them because the doctors will need to be added individually
Again, I'd assume this is an enhanced experience. Assume someone joins without an office already in the database. How would we set up an office then? What would it look like?



I mean, we have already discussed these things.. the Claim button should be a simple claim button and then leading to an area where they can confirm that they own the practice - for example a call to their office or an email to their office email directly asking for confirmation of ownership after they have entered that phone number/email into some type of profile for the office. I guess minimal data should be entered about the practice: address, phone number, email, specialty, and owner. Then the confirmation will be sent and the office will be on our database map.  Then a doctor can click a button on the office page to “link” to the office and be seen as a dentist profile at that office. This dentist will then get confirmation to their personal cell or personal email regarding this linking. When dentists create their own individual profile this can be without linking to an office initially and should have questions in signing in regarding what you have already designed for the “dentist page”

**Comment by Pcushing** [comment]
> When you go to http://pycky.com/patient/patient_search.html click search at the top. This will take you to the Skoulas Dentistry page (office page) Then you can click on the individual doctor and it
will take you to the doctor page.

Got it! I would've assumed that button would lead to search results, not an individual page. Not sure if that was just a way of exposing that page for now or that's how you'd imagine it working. We'll need to discuss before implementing. 

> If their office is already on the map - they Claim it as a dentist, enter all of this above information as a dentist so that they create their "dentist profile"

That's fine, but what about when there's a dentists that joins without their office being on the list?

> I mean, we have already discussed these things..

OK. This paragraph really highlights a gap to be addressed. What you've given me isn't nearly as well defined as you think. The mocks only cover about 60% of what I need right now. It shows how everything looks once populated but nothing about how we get there. That makes my job harder and ultimately costs you more if I build something that's not quite what you want because I had to guess.  Here's some examples just from your answer...

> the Claim button should be a simple claim button 

Where is the Claim button? The office page, presumably? What about if a dentist is joining and we don't have their office yet? Do we have a Claim step in the set up flow? Would we show offices in search results before there's any dentists? It seems like that's useful for dentists but bad for patients so now we have two separate search result pages. Unless we're only prompting for this in a sign up flow (which we dont have designed yet)? 

>  then leading to an area where they can confirm that they own the practice

Should it be in a modal over the map? Should it be it's own claim page? 

> for example a call to their office or an email to their office email directly asking for confirmation of ownership after they have entered that phone number/email 

Do we have any text on the page describing to the dentist what we're going to do with it? They might want to know before we reach out to their employer. Do we want to pick one for now?

> into some type of profile for the office.

Again, we have the finished profile for a dentist but no flow to get the data into here or form for what it might look like when edited.

>  I guess minimal data should be entered about the practice: address, phone number, email, specialty, and owner. 

Should it just be one page that asks for all of this information from the dentist?  Do you want to ask several small questions to avoid question fatigue? Whose email are we asking for? The owner? A secretary? Are we verifying that that's a legit email for the office before we send a confirmation email to the office? Are you asking for the dentists's specialty? Or the office's specialty?

> Then the confirmation will be sent and the office will be on our database map.

It sounds like the office wasnt on the map previously. How did we get to the claim step then?

> Then a doctor can click a button on the office page to “link” to the office and be seen as a dentist profile at that office.

Can they do this before an office is confirmed?

> should have questions in signing in regarding what you have already designed for the “dentist page”

I don't have a design / sign up flow for dentists. That's one of my requests.

These questions might seem like I'm just being difficult, but I have to ask myself every single one of these right now before doing anything. When there's a design, it indicates you+the designer already asked/answered the bulk of these. 

If you'd like, we can spend a meeting sketching this out on paper, but we'll need more dedicated time than we had last time. I'm also not sure I'd be cheaper than your designer for this work, but whether it's him or me, even a basic sketch of this flow would really help me. It's tough to design a product over email and in text like this.

As we get further into the project, I can more easily take my best guess at some of this as we'll have other examples, but we're not there.
